### ISSUE TITLE
[REQUEST]  Add Appveyor.yml to compile it online

### ISSUE THREAD

**Issue by ewwink** [openbullet/openbullet#244]
Some people doesn't know how to compile OB but we can use online service to compile it. I'm using this `appveyor.yml` to compile openbullet on https://www.appveyor.com

```YML
version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%
    git submodule update --init --recursive
    nuget restore OpenBullet.sln
build:
  verbosity: normal
after_build:
- cmd: 7z a OpenBullet.zip %APPVEYOR_BUILD_FOLDER%\openbullet\bin\debug\
artifacts:
- path: OpenBullet.zip
  name: OpenBullet
```

it take only a minute to compile and the compiled result https://ci.appveyor.com/project/ewwink/openbullet/build/artifacts
